# Generated by Django 6.0.6 on 2026-07-10 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='증상명')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '증상',
                'verbose_name_plural': '증상',
                'db_table': 'tracker_symptom',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='기록 날짜')),
                ('no_symptom', models.BooleanField(default=False, verbose_name='증상 없음')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '일일 기록',
                'verbose_name_plural': '일일 기록',
                'db_table': 'tracker_dailyrecord',
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SymptomEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.CharField(max_length=10, verbose_name='강도')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tracker.dailyrecord', verbose_name='일일 기록')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tracker.symptom', verbose_name='연결 증상')),
            ],
            options={
                'verbose_name': '증상 기록',
                'verbose_name_plural': '증상 기록',
                'db_table': 'tracker_symptomentry',
            },
        ),
    ]
