# Generated by Django 6.0.6 on 2026-07-10 02:13

from django.db import migrations

# 5개 증상 이름 및 순서 리스트화 -> db 저장
def create_symptoms(apps, schema_editor):

    # tracker 앱의 Symptom 모델 가져오기
    Symptom = apps.get_model('tracker', 'Symptom')

    symptoms = [
        ("안면홍조", 1),
        ("수면장애", 2),
        ("감정기복", 3),
        ("피로감", 4),
        ("관절통", 5),
    ]

    # 증상 저장
    for name, order in symptoms:
        Symptom.objects.create(name=name, order=order)


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_symptoms),
    ]
