# Generated by Django 6.0.6 on 2026-07-13 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_initial_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomentry',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_entries', to='tracker.symptom', verbose_name='연결 증상'),
        ),
    ]
