# Generated by Django 6.0.6 on 2026-07-13 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('memo', models.CharField(max_length=100, verbose_name='한 줄 소감')),
                ('image', models.ImageField(blank=True, null=True, upload_to='garden/', verbose_name='사진')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_records', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '정원 기록',
                'verbose_name_plural': '정원 기록',
                'db_table': 'garden_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
