# Generated by Django 6.0.6 on 2026-07-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='관리자', max_length=10, verbose_name='이름'),
            preserve_default=False,
        ),
    ]
