# Generated by Django 6.0.6 on 2026-07-09 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comment_notification',
            field=models.BooleanField(default=True, verbose_name='커뮤니티 댓글 알림'),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_notification',
            field=models.BooleanField(default=True, verbose_name='오늘 기록 알림'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_notification',
            field=models.BooleanField(default=False, verbose_name='커뮤니티 좋아요 알림'),
        ),
        migrations.AddField(
            model_name='user',
            name='reminder_time',
            field=models.TimeField(default=datetime.time(20, 0), verbose_name='기록 리마인더 시간'),
        ),
    ]
