# Generated by Django 6.0.6 on 2026-07-12 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1_answer', models.CharField(choices=[('A', '혼란기 경향'), ('B', '적응기 경향'), ('C', '재도약기 경향')], max_length=1)),
                ('q2_answer', models.CharField(choices=[('A', '혼란기 경향'), ('B', '적응기 경향'), ('C', '재도약기 경향')], max_length=1)),
                ('q3_answer', models.CharField(choices=[('A', '혼란기 경향'), ('B', '적응기 경향'), ('C', '재도약기 경향')], max_length=1)),
                ('q4_answer', models.CharField(choices=[('A', '혼란기 경향'), ('B', '적응기 경향'), ('C', '재도약기 경향')], max_length=1)),
                ('q5_answer', models.CharField(choices=[('A', '혼란기 경향'), ('B', '적응기 경향'), ('C', '재도약기 경향')], max_length=1)),
                ('a_count', models.PositiveSmallIntegerField(default=0)),
                ('b_count', models.PositiveSmallIntegerField(default=0)),
                ('c_count', models.PositiveSmallIntegerField(default=0)),
                ('stage', models.CharField(choices=[('confusion', '혼란기'), ('adaptation', '적응기'), ('restart', '재도약기')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '자가진단 결과',
                'verbose_name_plural': '자가진단 결과 목록',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='diagnosis_d_user_id_541e68_idx')],
            },
        ),
    ]
